Update dependencies
DiamondLightSource/python-hrpd-rebin pull request #1
Opened 2019-11-20 10:08 UTC by VictoriaBeilsten-Edmands

- Replace dlsio imports with scisoftpy
- Require one of PyQt4 or PySide in setup.py
- Add classifiers, url, description and author info to setup.py

2019-11-20 11:09 UTC, PeterC-DLS commented on setup.py
> +    import PySide
If this succeeds then add it as a dependency

2019-11-20 11:11 UTC, PeterC-DLS approved these changes

2019-11-20 15:42 UTC, PeterC-DLS requested changes
Just a change in setup.py needed

2019-11-21 11:21 UTC, VictoriaBeilsten-Edmands commented
PySide/ PyQt4 requirement removed from setup.py, but added a line in README to state they're required.

2019-11-21 11:27 UTC, PeterC-DLS commented on README
> +One of PySide>=1.2 or PyQt4>=4 is required.
Also need to print error messages when it occurs during import

2019-11-21 11:29 UTC, PeterC-DLS requested changes
As per comment on README

2019-11-21 14:19 UTC, PeterC-DLS approved these changes

2019-11-21 14:35 UTC, merged